### ISSUE TITLE
docx files missing from MAGIC array

### ISSUE THREAD

**Issue by jrmhaig** [mimemagicrb/mimemagic#110]
First of all, thank you so much for your tremendous effort today.

We have an issue due to `MimeMagic::MAGIC` missing the following entry for docx files:

```ruby
["application/vnd.openxmlformats-officedocument.wordprocessingml.document", [[0, "PK\u0003\u0004", [[0..5000, "[Content_Types].xml", [[0..5000, "word/"]]]]]]]
```

By digging into the code (and with my limited knowledge of Nokogiri) it looks as though this is being skipped because my `opendesktop.org.xml` file (installed today on Mac, but also on ruby:2.6.5-alpine3.10 docker images) does not contain a `<magic>...</magic>` section inside the `<mime-type type="application/vnd.openxmlformats-officedocument.wordprocessingml.document">` block. (See https://github.com/mimemagicrb/mimemagic/blob/78b9da8d911b6f9b21dad35bac3190dd35711bce/lib/mimemagic/tables.rb#L75-L79)

**Comment by jellybob** [comment]
This is an issue with the mime types file you're using, rather than with this gem. The gem just loads the mime type information you've provided it with and then applies the rules within it.

**Comment by olbrich** [comment]
It looks like an older version of mimemagic had some extra magic in place for office files that was removed in https://github.com/mimemagicrb/mimemagic/commit/0c9132141901ceaa298a563cdcd72896067f1dd6.

I'm not sure why this was removed since it seems to be adding magic that is not part of the original database.  Perhaps this works in newer versions, but in some cases it will need to be added back in order to properly handle MS Office files.

@jrmhaig if you re-implement the old overlay file, it may work properly for you again.
